#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

# Note the v1 in the filename refers to the version of the CustomResourceDefinition
# not any of the versions of API being defined.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: kafkaproxies.kroxylicious.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kroxylicious.io
  scope: Namespaced
  names:
    plural: kafkaproxies
    singular: kafkaproxy
    kind: KafkaProxy
    shortNames:
      - kp
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 63
                  pattern: "[a-z0-9]([a-z0-9-]*[a-z0-9])?"
            spec:
              type: object
              required: ["clusters", "listeners"]
              properties:
                listeners:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: ["name"]
                  minItems: 1
                  maxItems: 1 # is it a pain to have to evolve this in the CRD, vs erroring in the operator code?
                  items:
                    type: object
                    required: ["name", "port", "protocol", "tls"] # difference from Gateway - tls required
                    properties:
                      name:
                        description: |-
                          Name is the name of the Listener. This name MUST be unique within a
                          KafkaGateway.
                        maxLength: 253
                        minLength: 1
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                        type: string
                      port:
                        description: |-
                          Port is the network port. Multiple listeners may use the
                          same port, subject to the Listener compatibility rules.
                        format: int32
                        maximum: 65535
                        minimum: 1
                        type: integer
                      protocol:
                        description: |-
                          Protocol specifies the network protocol this listener expects to receive.
                        maxLength: 255
                        minLength: 1
                        pattern: ^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?$|[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*\/[A-Za-z0-9]+$
                        type: string
                      tls:
                        type: object
                        required: ["certificateRefs"] #difference from Gateway - certRefs required because we always terminate TLS
                        properties:
                          certificateRefs:
                            type: array
                            maxItems: 64 # limit from gateway API experimental 1.20
                            items:
                              type: object
                              required: ["name"]
                              properties:
                                group:
                                  default: ""
                                  description: |-
                                    Group is the group of the referent. For example, "gateway.networking.k8s.io".
                                    When unspecified or empty string, core API group is inferred.
                                  maxLength: 253
                                  pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                                  type: string
                                kind:
                                  default: Secret
                                  description: Kind is kind of the referent. For example
                                    "Secret".
                                  maxLength: 63
                                  minLength: 1
                                  pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                                  type: string
                                name:
                                  description: Name is the name of the referent.
                                  maxLength: 253
                                  minLength: 1
                                  type: string
                                namespace:
                                  description: |-
                                    Namespace is the namespace of the referenced object. When unspecified, the local
                                    namespace is inferred.
                                    
                                    Note that when a namespace different than the local namespace is specified,
                                    a ReferenceGrant object is required in the referent namespace to allow that
                                    namespace's owner to accept the reference. See the ReferenceGrant
                                    documentation for details.
                                  maxLength: 63
                                  minLength: 1
                                  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                                  type: string
                          mode:
                            default: Terminate
                            description: |-
                              Mode defines the TLS behavior for the TLS session initiated by the client.
                              There is one possible mode:
                              
                              - Terminate: The TLS session between the downstream client and the
                                Gateway is terminated at the Gateway. This mode requires certificates
                                to be specified in some way, such as populating the certificateRefs
                                field.
                            enum: # difference from Gateway, Passthrough not allowed
                              - Terminate
                            type: string
                clusters:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: ["name"]
                  items:
                    type: object
                    required: ["name", "upstream", "advertisedBrokers", "hostnames"]
                    properties:
                      name:
                        type: string
                        # The name is used as a prefix to a Service name
                        # and Service names must be RFC 1035 Label Names
                        maxLength: 63
                        pattern: "[a-z]([a-z0-9-]*[a-z0-9])?"
                      upstream:
                        type: object
                        required: ["bootstrapServers"]
                        properties:
                          bootstrapServers:
                            description: |
                              A comma separated list of Kafka broker addresses, e.g. "host1:port1,host2:port2".
                              This could be a single address if the cluster has a highly available (loadbalanced) bootstrap address. 
                              Otherwise you should list addresses for several brokers, so that a broker being down does not prevent bootstrapping.
                            type: string
                      advertisedBrokers:
                        type: array
                        x-kubernetes-list-type: set
                        items:
                          format: int32
                          type: integer
                      hostnames:
                        type: array
                        x-kubernetes-list-type: set
                        minItems: 1
                        maxItems: 1
                        items:
                          type: string
                          maxLength: 253
                          minLength: 1
                          pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9%])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ # Gateway regex plus we allow a % as last character of first section of domain, wildcard prefix not allowed
                      filters:
                        description: The filters to be used for this cluster. Each filter is a separate resource.
                        type: array
                        items:
                          # This is basically (Local)ObjectReference
                          type: object
                          properties:
                            group:
                              type: string
                            kind:
                              type: string
                            name:
                              type: string
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      properties:
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
            status:
              type: object
              properties:
                observedGeneration:
                  description: |
                    The metadata.generation that was observed during the last reconciliation by the operator.
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      lastTransitionTime:
                        description: |
                          lastTransitionTime is the last time the condition transitioned from one status to another. 
                          This should be when the underlying condition changed. 
                          If that is not known, then using the time when the API field changed is acceptable.
                        type: string
                        format: date-time
                      message:
                        description: |
                          message is a human readable message indicating details about the transition. 
                          This may be an empty string.
                        type: string
                      observedGeneration:
                        description: |
                          observedGeneration represents the .metadata.generation that the condition was set based upon. 
                          For instance, if .metadata.generation is currently 12, but the 
                          .status.conditions[x].observedGeneration is 9, the condition is out of date with 
                          respect to the current state of the instance.
                        type: integer
                      reason:
                        description: |
                          reason contains a programmatic identifier indicating the reason for the condition's last transition. 
                          Producers of specific condition types may define expected values and meanings for this field, 
                          and whether the values are considered a guaranteed API. 
                          The value should be a CamelCase string. 
                          This field may not be empty.
                        type: string
                      status:
                        description: status of the condition, one of True, False, Unknown.
                        type: string
                        enum: [ "True", "False", "Unknown" ]
                      type:
                        description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        type: string
                clusters:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: [ "name" ]
                  items:
                    type: object
                    required: ["name"]
                    properties:
                      name:
                        description: The name of the `spec.cluster`.
                        type: string
                      conditions:
                        description: The conditions associated with this cluster.
                        type: array
                        items:
                          type: object
                          properties:
                            lastTransitionTime:
                              description: |
                                lastTransitionTime is the last time the condition transitioned from one status to another. 
                                This should be when the underlying condition changed. 
                                If that is not known, then using the time when the API field changed is acceptable.
                              type: string
                              format: date-time
                            message:
                              description: |
                                message is a human readable message indicating details about the transition. 
                                This may be an empty string.
                              type: string
                            observedGeneration:
                              description: |
                                observedGeneration represents the .metadata.generation that the condition was set based upon. 
                                For instance, if .metadata.generation is currently 12, but the 
                                .status.conditions[x].observedGeneration is 9, the condition is out of date with 
                                respect to the current state of the instance.
                              type: integer
                            reason:
                              description: |
                                reason contains a programmatic identifier indicating the reason for the condition's last transition. 
                                Producers of specific condition types may define expected values and meanings for this field, 
                                and whether the values are considered a guaranteed API. 
                                The value should be a CamelCase string. 
                                This field may not be empty.
                              type: string
                            status:
                              description: status of the condition, one of True, False, Unknown.
                              type: string
                              enum: [ "True", "False", "Unknown" ]
                            type:
                              description: type of condition in CamelCase or in foo.example.com/CamelCase.
                              type: string
